language:
  - python
  - node_js
python: "3.5"
node_js:
  - 4
  - 5
  - 6
before_install:
  - npm i -g npm@latest
  - npm install
install:
  - "pip install -e .[test]"
script:
  - tox
  - npm install
  - npm test
notifications:
  email: false
