language:
  - python
  - node_js
python: "3.5"
node_js:
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm i -g npm@latest
  - npm install -g
install:
  - "pip install -e .[test]"
script:
  - tox
  - npm install
  - npm test
notifications:
  email: false
