# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_codearticlemodel_original_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='codearticlemodel',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='potentialideamodel',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repostmodel',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
