# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160523_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='codearticlemodel',
            name='tag',
            field=models.CharField(choices=[('Vent', 'Vent'), ('Tutorial', 'Tutorial'), ('Learning Journal', 'Learning Journal'), ('Observation', 'Observation'), ('General', 'General')], default='General', max_length=16),
        ),
    ]
