# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_codearticlemodel_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', jsonfield.fields.JSONField()),
            ],
        ),
    ]
