# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 00:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_statmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='statmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 25, 0, 2, 9, 813029, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statmodel',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 25, 0, 2, 14, 620865, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
