# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160525_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statmodel',
            name='value',
            field=models.TextField(),
        ),
    ]
